AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Description: Stori Challenge Application

Resources:
  StoriChallengeBucket:
    Type: AWS::S3::Bucket
    Properties:
      BucketName: stori-challenge
