AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Description: Stori Challenge Application

Resources:
  CsvUploaderFunction:
    Type: AWS::Serverless::Function
    Properties:
      FunctionName: CsvUploader
      Handler: main
      Runtime: provided.al2023  
      CodeUri: backend/handle-csv/ 
      Events:
        ApiGatewayEvent:
          Type: Api
          Properties:
            Path: /upload-csv
            Method: post

  EmailSenderFunction:
    Type: AWS::Serverless::Function
    Properties:
      FunctionName: EmailSender
      Handler: main  
      Runtime: provided.al2023  
      CodeUri: backend/send-email/  
      Events:
        ApiGatewayEvent:
          Type: Api
          Properties:
            Path: /send-email
            Method: post
