name: Backend

on:
 push:
    branches:
      - main

jobs:
 build_and_package:
    name: Build and Package
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Set up Go
      uses: actions/setup-go@v4
      with:
        go-version: '1.22'

    - name: Build and package handleCSV
      run: |
        cd backend/handleCSV
        GOOS=linux GOARCH=amd64 go build -o bootstrap
        zip handleCSV.zip bootstrap
        cd ../..

    - name: Build and package sendEmail
      run: |
        cd backend/sendEmail
        GOOS=linux GOARCH=amd64 go build -o bootstrap
        zip sendEmail.zip bootstrap
        cd ../..

    - name: Archive built artifacts
      uses: actions/upload-artifact@v4
      with:
        name: lambda-artifacts
        path: |
          backend/handleCSV/handleCSV.zip
          backend/sendEmail/sendEmail.zip
 deploy_to_aws:
    name: Deploy to AWS
    needs: build_and_package
    runs-on: ubuntu-latest

    steps:
    - name: Download artifacts
      uses: actions/download-artifact@v4
      with:
        name: lambda-artifacts

    - name: Configure AWS Credentials
      uses: aws-actions/configure-aws-credentials@v4
      with:
        aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
        aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        aws-region: us-east-1

    - name: Deploy sendEmail to AWS Lambda
      run: |
        aws lambda update-function-code --function-name sendEmail --zip-file fileb://sendEmail/sendEmail.zip
    - name: Deploy handleCSV to AWS Lambda
      run: |
        aws lambda update-function-code --function-name handleCSV --zip-file fileb://handleCSV/handleCSV.zip
